services:
  app:
    image: php:8.3-cli
    container_name: point
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]